defmodule AiControlWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ai_control

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_ai_control_key",
    signing_salt: "YuHwGGCT",
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:ai_control, :secure_cookies, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [log: false, connect_info: [session: @session_options]],
    longpoll: [log: false, connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ai_control,
    gzip: not code_reloading?,
    only: AiControlWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ai_control
  end

  plug AiControlWeb.ServerRequestId

  plug Plug.Telemetry,
    event_prefix: [:phoenix, :endpoint],
    log: {AiControlWeb.RequestLog, :level, []}

  plug AiControlWeb.GatewayIngress
  plug AiControlWeb.GatewayBody

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug AiControlWeb.Router
end
